In [1]:
import numpy as np
import pandas as pd
Final_1b=pd.read_csv(r"C:\Users\agrabia\Documents\Formation\Projet/Final_1b.csv")

In [2]:
Final_1b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348684 entries, 0 to 348683
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   IncidentNumber                 348684 non-null  object 
 1   CalYear                        348684 non-null  int64  
 2   HourOfCall                     348684 non-null  int64  
 3   IncidentGroup                  348684 non-null  int64  
 4   StopCodeDescription            348684 non-null  int64  
 5   PropertyCategory               348684 non-null  int64  
 6   AddressQualifier               348684 non-null  int64  
 7   ProperCase                     348684 non-null  int64  
 8   Easting_rounded                348684 non-null  int64  
 9   Northing_rounded               348684 non-null  int64  
 10  IncidentStationGround          348683 non-null  float64
 11  NumStationsWithPumpsAttending  348684 non-null  float64
 12  NumPumpsAttending             

In [3]:
Final_1b.head()

IncidentNumber  CalYear  HourOfCall  IncidentGroup  StopCodeDescription  \
0  000003-01012020     2020           0              2                    6   
1  000008-01012020     2020           0              1                    1   
2  000009-01012020     2020           0              2                    7   
3  000011-01012020     2020           0              1                    1   
4  000015-01012020     2020           0              1                    2   

   PropertyCategory  AddressQualifier  ProperCase  Easting_rounded  \
0                 4                 7          17           506750   
1                 4                 1          27           518250   
2                 7                 7          10           535350   
3                 5                11          32           527750   
4                 6                 3          29           522850   

   Northing_rounded  ...  AttendanceTimeSeconds  DeployedFromStation_Name  \
0            181550  ...                    324                      45.0   
1            174850  ...                    195                      77.0   
2            194250  ...                    426                      25.0   
3            171150  ...                    249                      91.0   
4            165950  ...                    526                      90.0   

   DateOfCall_bis  MinuteOfCall  DelayCodeId_bis  AFA Joursem  jour ferie  \
0      2020-01-01             6             12.0    0       2           1   
1      2020-01-01            11             12.0    1       2           1   
2      2020-01-01            11              9.0    0       2           1   
3      2020-01-01            12             12.0    1       2           1   
4      2020-01-01            12             12.0    0       2           1   

   vacances  COVID (fermeture ecoles)  
0         1                         0  
1         1                         0  
2         1                         0  
3         1                         0  
4         1                         0  

[5 rows x 29 columns]

In [4]:
Final_1b['DateOfCall_bis'] = pd.to_datetime(Final_1b['DateOfCall_bis'])
Final_1b=Final_1b.dropna()
Final_1b.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 346804 entries, 0 to 348683
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   IncidentNumber                 346804 non-null  object        
 1   CalYear                        346804 non-null  int64         
 2   HourOfCall                     346804 non-null  int64         
 3   IncidentGroup                  346804 non-null  int64         
 4   StopCodeDescription            346804 non-null  int64         
 5   PropertyCategory               346804 non-null  int64         
 6   AddressQualifier               346804 non-null  int64         
 7   ProperCase                     346804 non-null  int64         
 8   Easting_rounded                346804 non-null  int64         
 9   Northing_rounded               346804 non-null  int64         
 10  IncidentStationGround          346804 non-null  float64       
 11  

In [5]:
from sklearn import linear_model,preprocessing
from sklearn.model_selection import train_test_split

In [7]:
Final_1b['TravelTimeClass']=pd.qcut(Final_1b['TravelTimeSeconds'],4,labels=[0,1,2,3])

In [8]:
data=Final_1b.drop(['TravelTimeSeconds','TurnoutTimeSeconds','AttendanceTimeSeconds','Resource_Code','IncidentNumber',
                    'DateOfCall_bis','TravelTimeClass'], axis=1)
target=Final_1b['TravelTimeClass']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.2,random_state=66)

In [9]:
X_train_scaled=preprocessing.scale(X_train)
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_scaled=scaler.transform(X_train)
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_scaled=scaler.transform(X_test)

In [10]:
clf=linear_model.LogisticRegression()
clf.fit(X_train_scaled,y_train)
y_pred=clf.predict(X_test_scaled)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[8419 4416 3736  712]
 [7720 4722 4336  792]
 [6357 4144 4847 1854]
 [3805 2551 3824 7126]]


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.32      0.49      0.39     17283
           1       0.30      0.27      0.28     17570
           2       0.29      0.28      0.29     17202
           3       0.68      0.41      0.51     17306

    accuracy                           0.36     69361
   macro avg       0.40      0.36      0.37     69361
weighted avg       0.40      0.36      0.37     69361



In [13]:
clf.score(X_test,y_test)

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


0.24950620665792014

In [15]:
Final_1b['TravelTimeClass']=pd.qcut(Final_1b['TravelTimeSeconds'],3,labels=[0,1,2])
data=Final_1b.drop(['TravelTimeSeconds','TurnoutTimeSeconds','AttendanceTimeSeconds','Resource_Code','IncidentNumber',
                    'DateOfCall_bis','TravelTimeClass'], axis=1)
target=Final_1b['TravelTimeClass']
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.2,random_state=66)
X_train_scaled=preprocessing.scale(X_train)
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_scaled=scaler.transform(X_train)
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_scaled=scaler.transform(X_test)
clf=linear_model.LogisticRegression()
clf.fit(X_train_scaled,y_train)
y_pred=clf.predict(X_test_scaled)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))
print(clf.score(X_test,y_test))

[[13219  8131  1734]
 [11736  9028  2480]
 [ 6865  6953  9215]]
              precision    recall  f1-score   support

           0       0.42      0.57      0.48     23084
           1       0.37      0.39      0.38     23244
           2       0.69      0.40      0.51     23033

    accuracy                           0.45     69361
   macro avg       0.49      0.45      0.46     69361
weighted avg       0.49      0.45      0.46     69361

0.3320742203832125


C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [10]:
data=Final_1b.drop(['TravelTimeSeconds','TurnoutTimeSeconds','AttendanceTimeSeconds','Resource_Code','IncidentNumber',
                    'DateOfCall_bis','TravelTimeClass'], axis=1)
target=Final_1b['TravelTimeSeconds']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.2,random_state=66)

In [12]:
X_train_scaled=preprocessing.scale(X_train)
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_scaled=scaler.transform(X_train)
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_scaled=scaler.transform(X_test)

In [14]:
from sklearn import neighbors,model_selection,ensemble,svm

In [20]:
knn=neighbors.KNeighborsClassifier()
parametres={'n_neighbors':range(2,40)}
grid_knn=model_selection.GridSearchCV(estimator=knn,param_grid=parametres)
grid_knn.fit(X_train_scaled,y_train)

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(2, 40)})

In [21]:
print('Meilleurs paramètres:',grid_knn.best_params_)
print(grid_knn.score(X_test_scaled,y_test))
y_pred=grid_knn.predict(X_test_scaled)
pd.crosstab(y_test,y_pred)

Meilleurs paramètres: {'n_neighbors': 39}
0.004123354622914894


col_0              0.0    1.0    2.0    3.0    4.0    5.0    6.0    7.0    \
TravelTimeSeconds                                                           
0.0                    1     10      1      1      3      0      0      0   
1.0                    5     27      9      4      5      1      1      0   
2.0                    2     12      2      3      0      1      0      0   
3.0                    1      9      2      0      2      1      1      0   
4.0                    1     14      3      1      0      2      1      0   
...                  ...    ...    ...    ...    ...    ...    ...    ...   
1135.0                 0      0      1      0      0      0      0      0   
1139.0                 0      0      0      0      0      0      0      0   
1140.0                 0      0      0      0      0      0      0      0   
1154.0                 0      0      1      0      0      0      0      0   
1179.0                 0      0      0      0      0      0      0      0   

col_0              8.0    9.0    ...  723.0  725.0  733.0  751.0  762.0  \
TravelTimeSeconds                ...                                      
0.0                    0      0  ...      0      0      0      0      0   
1.0                    0      0  ...      0      0      0      0      0   
2.0                    0      0  ...      0      0      0      0      0   
3.0                    0      2  ...      0      0      0      0      0   
4.0                    1      0  ...      0      0      0      0      0   
...                  ...    ...  ...    ...    ...    ...    ...    ...   
1135.0                 0      0  ...      0      0      0      0      0   
1139.0                 0      0  ...      0      0      0      0      0   
1140.0                 0      0  ...      0      0      0      0      0   
1154.0                 0      0  ...      0      0      0      0      0   
1179.0                 0      0  ...      0      0      0      0      0   

col_0              795.0  804.0  823.0  881.0  938.0  
TravelTimeSeconds                                     
0.0                    0      0      0      0      0  
1.0                    0      0      0      0      0  
2.0                    0      0      0      0      0  
3.0                    0      0      0      0      0  
4.0                    0      0      0      0      0  
...                  ...    ...    ...    ...    ...  
1135.0                 0      0      0      0      0  
1139.0                 0      0      0      0      0  
1140.0                 0      0      0      0      0  
1154.0                 0      0      0      0      0  
1179.0                 0      0      0      0      0  

[1001 rows x 555 columns]

In [ ]:
svm_clf=svm.SVC(probability=True)
parametres={'C':[0.1,1,10,30],'kernel':['rbf','linear','sigmoid']}
grid_svm=model_selection.GridSearchCV(estimator=svm_clf,param_grid=parametres)
grid_svm.fit(X_train_scaled,y_train)
grid_svm.best_params_
print(grid_svm.score(X_test_scaled,y_test))
y_pred_svm=grid_svm.predict(X_test_scaled)
pd.crosstab(y_test,y_pred_svm)

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [17]:
rf=ensemble.RandomForestClassifier()
grid_rf=model_selection.GridSearchCV(estimator=rf, param_grid={'max_features':["squrt","log2",None]})
grid_rf.fit(X_train_scaled,y_train)
grid_rf.best_params_
print(grid_rf.score(X_test_scaled,y_test))
y_pred_rf=grid_rf.predict(X_test_scaled)
pd.crosstab(y_test,y_pred_rf)

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


ValueError: 
All the 15 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got 'squrt' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 473, in fit
    trees = Parallel(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
  File "sklearn\tree\_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 242, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 747, in sklearn.tree._tree.Tree._add_node
  File "sklearn\tree\_tree.pyx", line 719, in sklearn.tree._tree.Tree._resize_c
  File "sklearn\tree\_utils.pyx", line 35, in sklearn.tree._utils.safe_realloc
MemoryError: could not allocate 4680843264 bytes

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 473, in fit
    trees = Parallel(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
  File "sklearn\tree\_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 242, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 747, in sklearn.tree._tree.Tree._add_node
  File "sklearn\tree\_tree.pyx", line 719, in sklearn.tree._tree.Tree._resize_c
  File "sklearn\tree\_utils.pyx", line 35, in sklearn.tree._utils.safe_realloc
MemoryError: could not allocate 4689231872 bytes

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 473, in fit
    trees = Parallel(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
  File "sklearn\tree\_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 242, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 747, in sklearn.tree._tree.Tree._add_node
  File "sklearn\tree\_tree.pyx", line 719, in sklearn.tree._tree.Tree._resize_c
  File "sklearn\tree\_utils.pyx", line 35, in sklearn.tree._utils.safe_realloc
MemoryError: could not allocate 4676648960 bytes

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 473, in fit
    trees = Parallel(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
  File "sklearn\tree\_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 242, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 747, in sklearn.tree._tree.Tree._add_node
  File "sklearn\tree\_tree.pyx", line 719, in sklearn.tree._tree.Tree._resize_c
  File "sklearn\tree\_utils.pyx", line 35, in sklearn.tree._utils.safe_realloc
MemoryError: could not allocate 4685037568 bytes

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 473, in fit
    trees = Parallel(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 864, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 379, in fit
    builder.build(self.tree_, X, y, sample_weight)
  File "sklearn\tree\_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 242, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn\tree\_tree.pyx", line 747, in sklearn.tree._tree.Tree._add_node
  File "sklearn\tree\_tree.pyx", line 719, in sklearn.tree._tree.Tree._resize_c
  File "sklearn\tree\_utils.pyx", line 35, in sklearn.tree._utils.safe_realloc
MemoryError: could not allocate 4697620480 bytes


In [19]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

In [20]:
dtc=DecisionTreeClassifier()
ac=AdaBoostClassifier(base_estimator=dtc,n_estimators=400)
ac.fit(X_train_scaled,y_train)
ac.score(X_test_scaled,y_test)
y_pred_ac=ac.predict(X_test_scaled)
pd.crosstab(y_test,y_pred_ac)

C:\Users\agrabia\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


col_0              0.0     1.0     2.0     3.0     4.0     5.0     6.0     \
TravelTimeSeconds                                                           
0.0                     3       3       2       2       3       0       2   
1.0                     7      16       4       4       2       0       0   
2.0                     1       5       5       1       3       1       0   
3.0                     1       7       0       0       1       1       1   
4.0                     0       7       0       0       1       1       1   
...                   ...     ...     ...     ...     ...     ...     ...   
1135.0                  0       0       0       0       0       0       0   
1139.0                  0       0       0       0       0       0       0   
1140.0                  0       0       0       0       0       0       0   
1154.0                  0       0       0       0       0       0       0   
1179.0                  0       0       0       0       0       0       0   

col_0              7.0     8.0     9.0     ...  1088.0  1090.0  1092.0  \
TravelTimeSeconds                          ...                           
0.0                     0       0       0  ...       0       0       1   
1.0                     1       0       1  ...       0       0       0   
2.0                     1       0       0  ...       0       0       0   
3.0                     1       0       0  ...       0       0       0   
4.0                     0       0       0  ...       0       0       0   
...                   ...     ...     ...  ...     ...     ...     ...   
1135.0                  0       0       0  ...       0       0       0   
1139.0                  0       0       0  ...       0       0       0   
1140.0                  0       0       0  ...       0       0       0   
1154.0                  0       0       0  ...       0       0       0   
1179.0                  0       0       0  ...       0       0       0   

col_0              1093.0  1102.0  1110.0  1115.0  1119.0  1120.0  1128.0  
TravelTimeSeconds                                                          
0.0                     0       0       0       0       0       0       0  
1.0                     0       0       0       0       0       0       0  
2.0                     0       0       0       0       0       0       0  
3.0                     0       0       0       0       0       0       0  
4.0                     0       0       0       0       0       0       0  
...                   ...     ...     ...     ...     ...     ...     ...  
1135.0                  0       0       0       0       0       0       0  
1139.0                  0       0       0       0       0       0       0  
1140.0                  0       0       0       0       0       0       0  
1154.0                  0       0       0       0       0       0       0  
1179.0                  0       0       0       0       0       0       0  

[1001 rows x 954 columns]

In [22]:
ac.score(X_test_scaled,y_test)

0.0047288822248814175

In [23]:
rf=ensemble.RandomForestClassifier()
rf.fit(X_train_scaled,y_train)
print(rf.score(X_test_scaled,y_test))
y_pred_rf=rf.predict(X_test_scaled)
pd.crosstab(y_test,y_pred_rf)

MemoryError: could not allocate 4726980608 bytes

In [ ]:
svm_clf=svm.SVC(probability=True)
svm_clf.fit(X_train_scaled,y_train)
print(svm_clf.score(X_test_scaled,y_test))
y_pred_svm=svm_clf.predict(X_test_scaled)
pd.crosstab(y_test,y_pred_svm)